# fly.toml app configuration file generated for retell-backend-node-demo on 2024-03-20T18:07:28-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'retell-backend-node-demo'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
